runtime: nodejs12
handlers:
    - url: /settings
      static_files: build/index.html
      upload: build/index.html
      secure: always
      redirect_http_response_code: 301
      
    - url: /pods
      static_files: build/index.html
      upload: build/index.html
      secure: always
      redirect_http_response_code: 301

    - url: /about
      static_files: build/index.html
      upload: build/index.html
      secure: always
      redirect_http_response_code: 301

    - url: /ccd
      static_files: build/index.html
      upload: build/index.html
      secure: always
      redirect_http_response_code: 301

    - url: /privacy
      static_files: build/index.html
      upload: build/index.html
      secure: always
      redirect_http_response_code: 301
    
    - url: /
      static_files: build/index.html
      upload: build/index.html
      secure: always
      redirect_http_response_code: 301

    - url: /(.*)
      static_files: build/\1
      upload: build/(.*)
      secure: always
      redirect_http_response_code: 301
