runtime: nodejs12
handlers:
    - url: /help
      static_files: build/index.html
      upload: build/index.html
      secure: always
      redirect_http_response_code: 301

    - url: /privacy
      static_files: build/index.html
      upload: build/index.html
      secure: always
      redirect_http_response_code: 301

    - url: /ccd
      static_files: build/index.html
      upload: build/index.html
      secure: always
      redirect_http_response_code: 301
      
    - url: /covidsitters
      static_files: build/index.html
      upload: build/index.html
      secure: always
      redirect_http_response_code: 301

    - url: /covidsitters/settings
      static_files: build/index.html
      upload: build/index.html
      secure: always
      redirect_http_response_code: 301
      
    - url: /covidsitters/pods
      static_files: build/index.html
      upload: build/index.html
      secure: always
      redirect_http_response_code: 301

    - url: /hivesforheroes
      static_files: build/index.html
      upload: build/index.html
      secure: always
      redirect_http_response_code: 301

    - url: /hivesforheroes/settings
      static_files: build/index.html
      upload: build/index.html
      secure: always
      redirect_http_response_code: 301
      
    - url: /hivesforheroes/pods
      static_files: build/index.html
      upload: build/index.html
      secure: always
      redirect_http_response_code: 301

    - url: /
      static_files: build/index.html
      upload: build/index.html
      secure: always
      redirect_http_response_code: 301

    - url: /(.*)
      static_files: build/\1
      upload: build/(.*)
      secure: always
      redirect_http_response_code: 301
